### ISSUE TITLE
Group the lints

### ISSUE THREAD

**Issue by erikvader** [erikvader/MiniZinc-linter#2]
Could be a good idea to put all lint rules into groups or categories to be able to toggle them on or off more easily. Possible categories could be:
- **Safe**: rules with no false-positives, if they trigger they are correct.
- **Style**: rules only nagging on style.
- **Uncertain**: Something looks like it's wrong, but not sure.
- **Positive**: The compiler should be able to optimize something into a global constraint or something. 
- **MiniZinc challenge**: Enable all rules for the minizinc challenge

**Comment by Pierre-Flener** [comment]
Let's start with just "course" vs "challenge".

**Comment by erikvader** [comment]
Each rule must belong to exactly on category, and there is only for rule that fits in "challenge", so only having those two is too little.
I have added groups similar to what I suggested, so I am therefore closing this.
