### ISSUE TITLE
Eliminate disjunction

### ISSUE THREAD

**Issue by erikvader** [erikvader/MiniZinc-linter#25]
# Explanation
Disjunction (`\/`) is often a performance impact and can sometimes be reformulated to something that doesn't use disjunction.

# Examples
```minizinc
var 5..7: x;
var 4..8: y;
constraint x > 5 \/ y > 4;
```
Can eliminate the disjunction by instead writing:
```minizinc
constraint x + y > 5 + 4;
```

**Comment by erikvader** [comment]
This probably needs to be more general somehow or have more examples. Only checking against this very specific case is probably not so useful

**Comment by Pierre-Flener** [comment]
Just flag all disjunctions.

Highest priority!

**Comment by erikvader** [comment]
is covered by #18
