### ISSUE TITLE
Unconstrained variables

### ISSUE THREAD

**Issue by erikvader** [erikvader/MiniZinc-linter#3]
# Explanation
Variables should be constrained in some way, their results won't have any meaning otherwise. If a variable isn't constrained, then it should be removed or become constrained. An `array` will be treated as many separate variables.

# Examples
`v` is not constrained.
```minizinc
var int: v;
output [show(v)];
solve satisfy;
```
The second element of `a` is unconstrained.
```minizinc
array[1..2] of var int: a;
constraint a[1] = 2;
solve satisfy;
```
Here the array is sometimes constrained, depending on the value of `b`. This should count towards all values in `a` being constrained as `a` at least wasn't forgotten.
```minizinc
array[1..2] of var int: a;
var int: b;
constraint forall(i in 1..2)(if b = 1 then a[i] = 2 endif);
solve satisfy;
```

**Comment by Pierre-Flener** [comment]
Highest priority!

**Comment by erikvader** [comment]
merge into #1
